### ISSUE TITLE
AmqpSender#rxSendWithAck and AmqpSender#rxClose do not complete/fail on connection loss

### ISSUE THREAD

**Issue by JonasTaulien** [vert-x3/vertx-proton#130]
### Version
In our application we are using

* `vert.x:4.2.6`
* `vertx-amqp-client:4.2.6`
* `vertx-rx-java2:4.2.6`

And as a message broker we are using ActiveMQ Artemis in the version `2.21.0`.

### Context
We are trying to build a resilient connection to our message broker using AMQP.

### Do you have a reproducer?
For this I have created the following reproducer: https://github.com/JonasTaulien/vertx-amqp-client-reproducer

### Steps to reproduce
As written in the [README](https://github.com/JonasTaulien/vertx-amqp-client-reproducer) we have identified two behaviours, that we think are bugs:
When an AmqpSender could be successfully created, but when the connection breaks after that, the Completables returned by `rxSendWithAck` and `rxClose` do not complete.

We debugged the Vert.x code and the reason for the latter is that, even if `AmqpSenderImpl.close()` sets a closeHandler on the underlying ProtonSender, the ProtonSender never calls that close handler. That's why the Completable (returned by `rxClose`) never completes.

**Comment by gemmellr** [comment]
As Tim noted this is not a bug in vertx-proton, which is essentially a low level protocol handler and so fires based on actual protocol activity, allowing it to be handled and if appropriate responded to. It doesnt fire the link close handler in this case because the link actually did not explicitly close (and further, depending on precise link setup may even not be considered implicitly closed despite the disconnect). It will fire the connection disconnectHandler handler when the socket goes away as Tim also noted, which can be used to detect a premature disconnect.
