### ISSUE TITLE
Exposing AMQP idle-time-out through the ProtonConnection

### ISSUE THREAD

**Issue by ppatierno** [vert-x3/vertx-proton#34]
I see that some fields of the AMQP "open" performative are exposed through the ProtonConnection; for example the container-id (with setContainer) and hostname (with setHostname).

The idle-time-out is missing.

I propose to allow the user to set the idle-time-out using the ProtonConnection which internally should set such value on the ProtonTransport instance which handles the final Transport instance from ProtonJ which provides the setIdleTimeout() method for the "open" performative.

What do you think ?

**Comment by gemmellr** [comment]
I think I'd put it on the client and server options, and provide it to the transports when created.

This may warrant adjusting where/when the processing is done to satisfy/enforce both peers idle-timeouts.

**Comment by ppatierno** [comment]
@gemmellr It was my first idea but ... the ProtonClientOptions for example already exposes an idle timeout that is related to the derived NetClientOptions. I think that putting the "open" fields into client options can be confusing for user even because we already have some of them (container-id, hostname) in the ProtonConnection.

**Comment by gemmellr** [comment]
It does, and this is rather related functionality, so I think that it would make some sense to have them in the same place. I also don't think it makes for a nice server experience to have to configure this on every connection. It might complicate the handling having it on the connection since its in the transport where it actually occurs, we would need to be quite careful about when it gets set if its on the connection (which it isn't in Proton).

**Comment by ppatierno** [comment]
I agree on having them all in the same place but in order to have this settings in ProtonClientOptions and ProtonServerOptions, we should move the current settings (container-id, hostname, ...) from ProtonConnection to them and then adding the new ones like idle-time-timeout (even if in that case we should be careful to the name because as you know and I said before we already have the tcp related idle timeout).

Exposing these settings in the ProtonConnection instead could have the advantage to change some parameter from the user application (on the fly). For example, on server side when an "open" is received and the ProtonConnection is returned in the connectHandler, it could be useful to set a different idle-timeout in relation to the remote container-id (just as an example). I don't know if it could make sense to do. Having settings in the ProtonServerOptions doesn't allow this flexibility.

**Comment by gemmellr** [comment]
I don't think we should move those actually. Those may have connection-specific meaning, e.g a server could have multiple [virtual] hostnames.

Changing idle-timeout on the fly makes no sense, as it is an advertised value and there is specific enforcement of it that goes on as a result of whats advertised. I don't think a server would set different idle timeouts on different connections, there aren't any I'm aware of that can do that.

**Comment by ppatierno** [comment]
So your idea is to mix settings between ProtonConnection (container, hostname) and ProtonXXXOptions (idletimeout). In any case we have the naming problem in this specific case ... idle timeout is already booked :-)

**Comment by gemmellr** [comment]
Things that are likely to be connection-specific, suit the connection. Things that aren't likely to be, suit the options. I think this is more of a client/server level option than a connection specific one. That there is already connection timeout related config on the options, makes it doubly suitable in this case in my mind.  "AmqpIdleTimeout" would seem like a simple enough name. One could even rename the existing option to make it clearer, though I wouldn't personally. Or choose something different like Heartbeat and describe it (see recent circular discussion at Qpid on naming of these things :P)

**Comment by ppatierno** [comment]
It's possible I miss the naming discussion in the Qpid list (if you have the link to the archived discussion it could be great). Btw, what do you think about keep-alive timeout that is the same name as the corresponding MQTT parameter ?

**Comment by gemmellr** [comment]
You'd know if you'd read it, so I guess you didnt :P I have two links, as the thread split across both lists at points. 
http://qpid.2158936.n2.nabble.com/API-and-terms-idle-time-out-and-heartbeat-intervals-tp7651224.html
http://qpid.2158936.n2.nabble.com/Re-API-and-terms-idle-time-out-and-heartbeat-intervals-tp7651369.html

I don't have a particular issue with the name so long as it documents what it does. In some regards using an related MQTT name might be confusing since its not MQTT related here, more so as there is an option that already aligns with the AMQP name, and folks might confuse it with TCP keep alive...on the other hand, I think its simply confusing regardless what you call it, folks will need to read the API to see what it actually does, and I don't expect too many folks to use it.

**Comment by ppatierno** [comment]
My opinion is that the current idle timeout should be renamed in TCP idle timeout and the new one as you said could be AMQP idle timeout.

**Comment by gemmellr** [comment]
I'd probably not bother renaming the existing one, but I could live with doing so. I doubt many folks are using either currently. Neither should be used without reading what they do, and it'll be fairly obvious it didn't do what you want if you do.

Now that I said the above, I realise renaming the current one is more problematic, since it is inherited. So yeah, I'd personally just leave it as it is.

**Comment by ppatierno** [comment]
You're right but I'm quite sure that people won't read documentation and will try to set the amqp idle timeout using the wrong setter and not the heartbeat. Btw I'll move forward on adding heartbeat to ProtonXXXXOptions ... it's possible that I'll be the only one to use it :)

**Comment by ppatierno** [comment]
Feature added on behalf of f161f41b1d670c86f409ae97d5eadeb518c9c0b4

**Comment by sophokles73** [comment]
I have also used the `ProtonServerOptions.setHeartbeat()` but was very confused by its name because it doesn't have to do anything with a heartbeat but simply corresponds to the idle timeout value announced by the server to a client during connection establishment. Whether a client uses this value to actually send empty frames (a *heartbeat*) to keep up the connection is completely up to the client.
If at all possible I therefore would strongly suggest to use something along the lines of `setAmqpConnectionIdleTimeout` as suggested by @ppatierno as well ...

**Comment by gemmellr** [comment]
Yes, that is how it is intended/specified to work, and how heartbeating/idle-timeout works in AMQP 1.0 in general, you tell the other side your requirements, they need to satisfy them you enforce them.

I actually suggested "AmqpIdleTimeout" as name for it originally, and per the linked conversations don't particularly like 'heartbeat', but I also don't think there is a value or method of operation that can be selected here that wont confuse someone at some point. The main thing for me is that it says what it does.
