### ISSUE TITLE
close handler for link doesn't get passed the link in question if an error condition was set

### ISSUE THREAD

**Issue by grs** [vert-x3/vertx-proton#37]
If a link is detached with an error, the handle() method of the handler is invoked with AsynchResult having succeeded() returning false (which is not entirely unreasonable), but the link itself cannot then be retrieved from result(), which is a bit annoying. It can be worked around of course, but it would be easier to write handler if you *could* get the receiver from the parameter to the handler.

**Comment by gemmellr** [comment]
Failed results don't return values in vertx ("The result of the operation. This will be null if the operation failed."), so theres no way to do that without changing it to use a custom result type. Since you already have the link when you set the close handler for it, you can simply refer to it (e.g using a lambda for the handler), which I presume is the workaround you reference.

**Comment by grs** [comment]
Fair enough; seems a little weird to me that if the close is successful you do get the link, but when there is an error you don't though the first thing you will want to do is get the error condition on the link. However I can understand not wanting to change the API (and really my comment is more that AsyncResult seems less useful for close).

**Comment by gemmellr** [comment]
I agree its a little odd, I might not have written it that way myself, but at the same time its nicer in some ways than having custom types in there (Handler can't handle multiple args either, so I don't think there are alternatives that wouldn't involve that).

**Comment by gemmellr** [comment]
(marked duplicate to avoid for release notes)
