### ISSUE TITLE
ProtonConnection connection returns "is connected" after call to "disconnect"

### ISSUE THREAD

**Issue by ctron** [vert-x3/vertx-proton#64]
First of all, I am not saying this is a bug in vertx-proton, but it looks like people have a different expectation around the "disconnect" behavior of vertx-proton. So the solution might be to just clean up the docs.

The javadoc around "disconnect" simply says:

> Disconnects the underlying transport connection

Assuming the following code:

~~~java
ProtonConnection c = …;
c.isDisconnected (); // returns "false" -> connected
c.disconnect();
c.isDisconnected (); // still returns "false" -> connected
~~~

Based on the javadoc my expectation would be that the second call to "isDisconnected" returns `true`, as I just called disconnect.

**Comment by ctron** [comment]
More complete example:

~~~java
import io.vertx.core.Vertx;
import io.vertx.proton.ProtonClient;
import io.vertx.proton.ProtonClientOptions;
import io.vertx.proton.ProtonConnection;

public class Application4 {

    public static void main(String[] args) throws InterruptedException {

        Vertx vertx = Vertx.factory.vertx();

        ProtonClient client = ProtonClient.create(vertx);

        ProtonClientOptions options = new ProtonClientOptions();

        options.setSsl(true); 
        options.setTrustAll(true); // DONT' USE THIS …
        options.setHostnameVerificationAlgorithm(""); // … IN PRODUCTION!

        client.connect(options, "my-host", 4711, "my-user", "my-password", ac -> {

            if (ac.failed()) {
                System.out.println("Failed!");
                return;
            }

            ProtonConnection c = ac.result();
            System.out.format("IsDisconnected = %s%n", c.isDisconnected());
            c.disconnect();
            System.out.format("IsDisconnected = %s%n", c.isDisconnected());

            System.exit(0);
        });

        Thread.sleep(Long.MAX_VALUE);
    }
}
~~~

**Comment by vietj** [comment]
@gemmellr wha'ts your opinion ?

**Comment by gemmellr** [comment]
I have updated the javadoc to clarify the actual behaviour, which remains unchanged.

I agree the existing doc wasn't clear enough and I might not have implemented it the way it is, but looking into the impl plus underlying behaviour of the NetClient/NetSocket (which work the same but dont have an isDisconnected equivalent, perhaps for reasons such as this) I can see why someone might have done it that way, and so I think its best left as-is but clarified.

**Comment by vietj** [comment]
thanks @gemmellr

**Comment by dejanb** [comment]
@gemmellr I think we can at least set transport to be null on disconnect(), which would make its behavior more consistent.

**Comment by gemmellr** [comment]
I don't entirely agree there, I don't think it is inconsistent so much as the isDisconnected method just wasn't implemented to report what some folks might have wanted it to.

Changing things to make it say isDisconnected=true immediately after disconnect is called would have its own oddities from others perspective, since it will then return true and at a later point the disconnectHandler will be fired when it actually completes the disconnect.

If an app is calling disconnect, I think its reasonable to require that it knows itself it has if it needs to before the handler fires. If it needs somewhere to remember it the connection attachments() record could perhaps be used to store such information.

The isDisconnected method probably just wouldn't exist if I had implemented the disconnect bits, but anyone using it already could see an unexpected change in behaviour by adjusting it and so even if I thought it was the way to go I doubt I'd choose an x.y.1 release to do it.
