### ISSUE TITLE
remoteOfferedCapabilities access

### ISSUE THREAD

**Issue by ashertarno** [vert-x3/vertx-proton#74]
using proton under vertx amqp bridge with rabbitmq broker i must explicitly set 
'ANONYMOUS-RELAY' Symbol  in remote_offered_capabilities. I can't find any api for doing that.

**Comment by gemmellr** [comment]
I've responded on your original email already to cover why this doesn't make sense, and likely wouldnt help anyway, but I'll flesh this out with a little extra detail.

There is no way to set the remote offered capabilities, because they are sent by the peer (i.e RabbitMQ in this case), so there is only a getter to retrieve them.

**Comment by ashertarno** [comment]
thanks a lot, i was sure this could be set manually if not provided by the broker. cheers
