### ISSUE TITLE
Throw specific SaslException to indicate mechanism mismatch

### ISSUE THREAD

**Issue by sophokles73** [vert-x3/vertx-proton#95]
The `ProtonSaslClientAuthenticatorImpl` currently fails a SASL handshake with a (permanent) `SaslSystemException`. However, since there is no problem with the server side of the handshake, a `javax.security.sasl.AuthenticationException` (or a subclass thereof) seems to be more appropriate in this case FMPOV.

**Comment by gemmellr** [comment]
I agree that it shouldn't throw SaslSystemException given how it is specifically defined to represent the SYS_<foo> failure outcomes, I've missed that when you added it originally.

I don't agree that it should throw an AuthenticationException though based on its description. The base SaslException or another subclass seems more appropriate for the case that SASL couldn't proceed at all because the server doesn't offer a usable mechanism.

**Comment by sophokles73** [comment]
I am fine with using another specific subclass of SaslException as well. I can update my PR accordingly ...

**Comment by gemmellr** [comment]
Oops, hadn't noticed you already raised a pull request, didn't get notified about it :)

**Comment by sophokles73** [comment]
@gemmellr have already updated it also ;-)

**Comment by gemmellr** [comment]
Yep, I already commented on it twice now ;)

**Comment by sophokles73** [comment]
didn't get notified ... just kidding :-)

**Comment by gemmellr** [comment]
PR #97 Merged to master and picked to 3.7 branch for 3.7.0
